name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: deploy synapse ws
        uses: azure/synapse-workspace-deployment@release-1.0
        with:
          TargetWorkspaceName: 'divy-synapse-ws-prod'
#           TemplateFile: './divy-synapse-ws/TemplateForWorkspace.json'
#           ParametersFile: './divy-synapse-ws/TemplateParametersForWorkspace.json'
#           OverrideArmParameters: './divy-synapse/.github/workflows/main.yaml'
          environment: 'Azure Public'
          resourceGroup: 'divy_proj'
          clientId: ${{ secrets.CLIENTID }}
          clientSecret: ${{ secrets.CLIENTSECRET }}
          subscriptionId: ${{ secrets.SUBSCRIPTIONID }}
          tenantId: ${{ secrets.TENANTID }}
          DeleteArtifactsNotInTemplate: 'true'
          managedIdentity: 'False'
